### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by iondarie** [peros550/esp-homekit-ac-daikin#1]
Hello,

Is there any chance you could release the source code so i can try to modify it to work with my Gree AC ?

Thank you,

**Comment by peros550** [comment]
Sorry for my late answer. I have uploaded the full code here. This repo only holds the binaries for the OTA updates. 
https://github.com/peros550/esp-homekit-multiple-sensors

You have good chances to find the IR commands for Gree AC in that repository. Otherwise, you would only need to replace the IR commands with those that work for your own A/C
